language: generic 
sudo: required
services: 
  - docker

before_install: 
  - docker build -t nghiatn1998/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true nghiatn1998/docker-react npm run test